### YamlMime:JavaType
uid: "com.microsoft.signalr.HubException"
fullName: "com.microsoft.signalr.HubException"
name: "HubException"
nameWithType: "HubException"
summary: "An exception thrown when the server fails to invoke a Hub method."
inheritances:
- "<xref href=\"java.lang.Object?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
- "<xref href=\"java.lang.Throwable?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
- "<xref href=\"java.lang.Exception?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
- "<xref href=\"java.lang.RuntimeException?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
inheritedMembers:
- "java.lang.Object.clone()"
- "java.lang.Object.equals(java.lang.Object)"
- "java.lang.Object.finalize()"
- "java.lang.Object.getClass()"
- "java.lang.Object.hashCode()"
- "java.lang.Object.notify()"
- "java.lang.Object.notifyAll()"
- "java.lang.Object.wait()"
- "java.lang.Object.wait(long)"
- "java.lang.Object.wait(long,int)"
- "java.lang.Throwable.addSuppressed(java.lang.Throwable)"
- "java.lang.Throwable.fillInStackTrace()"
- "java.lang.Throwable.getCause()"
- "java.lang.Throwable.getLocalizedMessage()"
- "java.lang.Throwable.getMessage()"
- "java.lang.Throwable.getStackTrace()"
- "java.lang.Throwable.getSuppressed()"
- "java.lang.Throwable.initCause(java.lang.Throwable)"
- "java.lang.Throwable.printStackTrace()"
- "java.lang.Throwable.printStackTrace(java.io.PrintStream)"
- "java.lang.Throwable.printStackTrace(java.io.PrintWriter)"
- "java.lang.Throwable.setStackTrace(java.lang.StackTraceElement[])"
- "java.lang.Throwable.toString()"
syntax: "public class HubException extends RuntimeException"
constructors:
- uid: "com.microsoft.signalr.HubException.HubException()"
  fullName: "com.microsoft.signalr.HubException.HubException()"
  name: "HubException()"
  nameWithType: "HubException.HubException()"
  summary: "Initializes a new instance of the <xref uid=\"com.microsoft.signalr.HubException\" data-throw-if-not-resolved=\"false\" data-raw-source=\"HubException\"></xref> class."
  syntax: "public HubException()"
  desc: "Initializes a new instance of the <xref uid=\"com.microsoft.signalr.HubException\" data-throw-if-not-resolved=\"false\" data-raw-source=\"HubException\"></xref> class."
- uid: "com.microsoft.signalr.HubException.HubException(java.lang.String)"
  fullName: "com.microsoft.signalr.HubException.HubException(String errorMessage)"
  name: "HubException(String errorMessage)"
  nameWithType: "HubException.HubException(String errorMessage)"
  summary: "Initializes a new instance of the <xref uid=\"com.microsoft.signalr.HubException\" data-throw-if-not-resolved=\"false\" data-raw-source=\"HubException\"></xref> class with a specified error message."
  parameters:
  - description: "The error message that explains the reason for the exception."
    name: "errorMessage"
    type: "<xref href=\"java.lang.String?alt=java.lang.String&text=String\" data-throw-if-not-resolved=\"False\" />"
  syntax: "public HubException(String errorMessage)"
  desc: "Initializes a new instance of the <xref uid=\"com.microsoft.signalr.HubException\" data-throw-if-not-resolved=\"false\" data-raw-source=\"HubException\"></xref> class with a specified error message."
- uid: "com.microsoft.signalr.HubException.HubException(java.lang.String,java.lang.Exception)"
  fullName: "com.microsoft.signalr.HubException.HubException(String errorMessage, Exception innerException)"
  name: "HubException(String errorMessage, Exception innerException)"
  nameWithType: "HubException.HubException(String errorMessage, Exception innerException)"
  summary: "Initializes a new instance of the <xref uid=\"com.microsoft.signalr.HubException\" data-throw-if-not-resolved=\"false\" data-raw-source=\"HubException\"></xref> class with a specified error message and a reference to the exception that is the cause of this exception."
  parameters:
  - description: "The error message that explains the reason for the exception."
    name: "errorMessage"
    type: "<xref href=\"java.lang.String?alt=java.lang.String&text=String\" data-throw-if-not-resolved=\"False\" />"
  - description: "The exception that is the cause of the current exception, or null if no inner exception is specified."
    name: "innerException"
    type: "<xref href=\"java.lang.Exception?alt=java.lang.Exception&text=Exception\" data-throw-if-not-resolved=\"False\" />"
  syntax: "public HubException(String errorMessage, Exception innerException)"
  desc: "Initializes a new instance of the <xref uid=\"com.microsoft.signalr.HubException\" data-throw-if-not-resolved=\"false\" data-raw-source=\"HubException\"></xref> class with a specified error message and a reference to the exception that is the cause of this exception."
type: "class"
desc: "An exception thrown when the server fails to invoke a Hub method."
metadata: {}
package: "com.microsoft.signalr"
artifact: com.microsoft.signalr:signalr:5.0.10
